version: '3.8'

services:
  frontend:
    build: 
      context: \\wsl.localhost\Ubuntu-24.04\home\tgm\School\IST130\final-project
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - \\wsl.localhost\Ubuntu-24.04\home\tgm\School\IST130\final-project:/app
    networks:
      - app-network
    ports:
      - "130:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - WATCHPACK_POLLING=true

networks:
  app-network:
